### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#160]
Hello,

I am having this below error when running npm run dev on nodejs v10.15.0 and npm v6.7.0

...

┌─[offensive@parrot]─[/var/www/laravel/netcoscan]
└──╼ $npm run dev

> @ dev /var/www/laravel/netcoscan
> npm run development

> @ development /var/www/laravel/netcoscan
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/var/www/laravel/netcoscan/webpack.mix.js:18
mix.webpackConfig({
    ^

TypeError: Cannot read property 'webpackConfig' of undefined
    at Object.<anonymous> (/var/www/laravel/netcoscan/webpack.mix.js:18:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/var/www/laravel/netcoscan/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/offensive/.npm/_logs/2019-02-02T09_52_21_807Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/offensive/.npm/_logs/2019-02-02T09_52_21_865Z-debug.log
`

**Comment by jcc** [comment]
You try to upgrade the package of `laravel-mix`.

**Comment by m2ura** [comment]
npm install laravel-mix@4.0.0?

**Comment by jcc** [comment]
Yes
